### ISSUE TITLE
v/vee

### ISSUE THREAD

**Issue by fireballin** [WalkTheEarth/Blahaj#1]
1. Have you checked names.txt to check if It's already there? (go to [Names.txt](https://raw.githubusercontent.com/WalkTheEarth/Blahaj/main/names.txt) and use Ctrl+f to check)

2. What name is it?

3. (OPTIONAL) Have you made a pull request for it? (E.g., cloning the repo, adding your name then proposing changes?) (If not, just put N/A)

**Comment by WalkTheEarth** [comment]
Just vee?
ok

**Comment by fireballin** [comment]
or v as in the player character from cyberpunk 2077

**Comment by WalkTheEarth** [comment]
too late now lmao
