### ISSUE TITLE
Leo

### ISSUE THREAD

**Issue by eleanordoesntcode** [WalkTheEarth/Blahaj#3]
1. Have you checked names.txt to check if It's already there? (go to [Names.txt](https://raw.githubusercontent.com/WalkTheEarth/Blahaj/main/names.txt) and use Ctrl+f to check) yes

2. What name is it? Leo

3. (OPTIONAL) Have you made a pull request for it? (E.g., cloning the repo, adding your name then proposing changes?) (If not, just put N/A) #2

**Comment by WalkTheEarth** [comment]
very cool
